set guioptions-=a guioptions-=e guioptions-=m guioptions-=t guioptions-=T
set guioptions+=c
set linespace=1
set lines=30 columns=100

if g:vimrc#is_windows
  set guifont=Consolas:h10.5 guifontwide=ＭＳ_ゴシック:h12
  silent! set guifont=Fira\ Code\ Retina:h10 guifontwide=Cica:h12
elseif g:vimrc#is_unix
  set guifont=DejaVu\ Sans\ Mono\ 12
  silent! set guifont=MyricaM\ M\ 12 guifontwide=MyricaM\ M\ 12
endif

if !g:vimrc#is_nvim
  if g:vimrc#is_windows
    if has('kaoriya')
      Autocmd GUIEnter * set transparency=235
    elseif exists(':VimTweak') > 0
      Autocmd GUIEnter * VimTweakSetAlpha 235
    endif
  endif
else
  if exists(':GuiWindowOpacity') ==# 2
    GuiWindowOpacity 0.9
  endif
endif

if get(g:, 'colors_name', 'desert') ==# 'desert' || g:colors_name ==# 'morning'
  colorscheme torte
endif

source $VIMRUNTIME/delmenu.vim
if g:vimrc#is_windows
  set langmenu=ja_jp.cp932
elseif g:vimrc#is_unix
  set langmenu=ja_jp.utf-8
endif
" source $VIMRUNTIME/menu.vim
