set guioptions-=a guioptions-=e guioptions-=m guioptions-=t guioptions-=T
set guioptions+=c
set linespace=1
set lines=30 columns=100

if g:vimrc#is_windows
  set guifont=Consolas:h10.5 guifontwide=ＭＳ_ゴシック:h12
  silent! set guifont=Fira\ Code\ Retina:h10 guifontwide=Cica:h12
elseif g:vimrc#is_unix
  set guifont=DejaVu\ Sans\ Mono\ 12
  silent! set guifont=MyricaM\ M\ 12 guifontwide=MyricaM\ M\ 12
endif

if has('kaoriya')
  set transparency=235
elseif has('nvim')
  if exists(':GuiWindowOpacity') ==# 2
    GuiWindowOpacity 0.9
  endif
else
  Autocmd GUIEnter *
      \ if exists(':VimTweakSetAlpha') ==# 2 |
      \   Autocmd GUIEnter * VimTweakSetAlpha 235 |
      \ endif
endif

if get(g:, 'colors_name', 'desert') ==# 'desert'
  colorscheme torte
endif

source $VIMRUNTIME/delmenu.vim
if g:vimrc#is_windows
  set langmenu=ja_jp.cp932
elseif g:vimrc#is_unix
  set langmenu=ja_jp.utf-8
endif
" source $VIMRUNTIME/menu.vim
